//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwsWrapperDataProvider.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AwsWrapperDataProvider.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AuroraInitialConnectionStrategyPlugin_GetReader_InvalidHostSelectionStrategy {
            get {
                return ResourceManager.GetString("AuroraInitialConnectionStrategyPlugin_GetReader_InvalidHostSelectionStrategy", resourceCulture);
            }
        }
        
        internal static string AuroraInitialConnectionStrategyPlugin_InitHostProvider_RequiresDynamicProvider {
            get {
                return ResourceManager.GetString("AuroraInitialConnectionStrategyPlugin_InitHostProvider_RequiresDynamicProvider", resourceCulture);
            }
        }
        
        internal static string AuroraStaleDnsHelper_OpenVerifiedConnectionAsync_ClusterEndpointResolved {
            get {
                return ResourceManager.GetString("AuroraStaleDnsHelper_OpenVerifiedConnectionAsync_ClusterEndpointResolved", resourceCulture);
            }
        }
        
        internal static string AuroraStaleDnsHelper_OpenVerifiedConnectionAsync_CurrentConnectionRole {
            get {
                return ResourceManager.GetString("AuroraStaleDnsHelper_OpenVerifiedConnectionAsync_CurrentConnectionRole", resourceCulture);
            }
        }
        
        internal static string AuroraStaleDnsHelper_OpenVerifiedConnectionAsync_StaleDnsDetected {
            get {
                return ResourceManager.GetString("AuroraStaleDnsHelper_OpenVerifiedConnectionAsync_StaleDnsDetected", resourceCulture);
            }
        }
        
        internal static string AuroraStaleDnsHelper_OpenVerifiedConnectionAsync_WriterHostAddress {
            get {
                return ResourceManager.GetString("AuroraStaleDnsHelper_OpenVerifiedConnectionAsync_WriterHostAddress", resourceCulture);
            }
        }
        
        internal static string AuroraStaleDnsHelper_OpenVerifiedConnectionAsync_WriterHostSpec {
            get {
                return ResourceManager.GetString("AuroraStaleDnsHelper_OpenVerifiedConnectionAsync_WriterHostSpec", resourceCulture);
            }
        }
        
        internal static string AuroraStaleDnsHelper_OpenVerifiedConnectionAsync_WriterNotInAllowedHosts {
            get {
                return ResourceManager.GetString("AuroraStaleDnsHelper_OpenVerifiedConnectionAsync_WriterNotInAllowedHosts", resourceCulture);
            }
        }
        
        internal static string AwsWrapperCommand_SetCurrentConnection_TargetConnectionUpdating {
            get {
                return ResourceManager.GetString("AwsWrapperCommand_SetCurrentConnection_TargetConnectionUpdating", resourceCulture);
            }
        }
        
        internal static string AwsWrapperConnection_BeginDbTransaction_Called {
            get {
                return ResourceManager.GetString("AwsWrapperConnection_BeginDbTransaction_Called", resourceCulture);
            }
        }
        
        internal static string AwsWrapperConnection_CreateCommand_DbCommandCreated {
            get {
                return ResourceManager.GetString("AwsWrapperConnection_CreateCommand_DbCommandCreated", resourceCulture);
            }
        }
        
        internal static string AwsWrapperConnection_Dispose_DisposingTargetConnection {
            get {
                return ResourceManager.GetString("AwsWrapperConnection_Dispose_DisposingTargetConnection", resourceCulture);
            }
        }
        
        internal static string AwsWrapperProperty_SslValidationIsDisabled {
            get {
                return ResourceManager.GetString("AwsWrapperProperty_SslValidationIsDisabled", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_ErrorFetchingTopology {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.ErrorFetchingTopology", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_ErrorGettingNetworkTimeout {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.ErrorGettingNetworkTimeout", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_ErrorProcessingQueryResults {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.ErrorProcessingQueryResults", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_ExceptionDuringMonitoringStop {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.ExceptionDuringMonitoringStop", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_IgnoringTopologyRequest {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.IgnoringTopologyRequest", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_Interrupted {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.Interrupted", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_InvalidQuery {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.InvalidQuery", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_InvalidTopology {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.InvalidTopology", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_OpenedMonitoringConnection {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.OpenedMonitoringConnection", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_StartMonitoringThread {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.StartMonitoringThread", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_StartingNodeMonitoringThreads {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.StartingNodeMonitoringThreads", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_StopMonitoringThread {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.StopMonitoringThread", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_TimeoutSetToZero {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.TimeoutSetToZero", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_TopologyNotUpdated {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.TopologyNotUpdated", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_UnexpectedTopologyQueryColumnCount {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.UnexpectedTopologyQueryColumnCount", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_WriterMonitoringConnection {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.WriterMonitoringConnection", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_WriterPickedUpFromNodeMonitors {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor.WriterPickedUpFromNodeMonitors", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_DisposeConnectionAsync_ConnectionDisposed {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor_DisposeConnectionAsync_ConnectionDisposed", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_Dispose_DisposingClusterTopologyMonitor {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor_Dispose_DisposingClusterTopologyMonitor", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_Dispose_ErrorOccured {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor_Dispose_ErrorOccured", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_ExceptionIgnoredTopologyMonitoringConnection {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor_ExceptionIgnoredTopologyMonitoringConnection", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_QueryForTopologyAsync {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor_QueryForTopologyAsync", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_ReaderThreadFetchTopologyAsync_ExceptionIgnored {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor_ReaderThreadFetchTopologyAsync_ExceptionIgnored", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_RunMonitoringLoop_CancellingMonitoringNodes {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor_RunMonitoringLoop_CancellingMonitoringNodes", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_RunMonitoringLoop_Clearing {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor_RunMonitoringLoop_Clearing", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_RunMonitoringLoop_CurrentTopology {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor_RunMonitoringLoop_CurrentTopology", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_RunMonitoringLoop_FoundHosts {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor_RunMonitoringLoop_FoundHosts", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_RunMonitoringLoop_IsNotRdsInstance {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor_RunMonitoringLoop_IsNotRdsInstance", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_RunMonitoringLoop_IsRdsInstance {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor_RunMonitoringLoop_IsRdsInstance", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_RunMonitoringLoop_MonitoringTask {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor_RunMonitoringLoop_MonitoringTask", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_RunMonitoringLoop_MonitoringTime {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor_RunMonitoringLoop_MonitoringTime", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_RunMonitoringLoop_NodeFailedShutdown {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor_RunMonitoringLoop_NodeFailedShutdown", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_RunMonitoringLoop_NullConnection {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor_RunMonitoringLoop_NullConnection", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_RunMonitoringLoop_RegularMode {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor_RunMonitoringLoop_RegularMode", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_RunMonitoringLoop_RestartCancellationToken {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor_RunMonitoringLoop_RestartCancellationToken", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_RunMonitoringLoop_TopologyNotUpdated {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor_RunMonitoringLoop_TopologyNotUpdated", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_RunMonitoringLoop_TopologyUpdated {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor_RunMonitoringLoop_TopologyUpdated", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_RunMonitoringLoop_WaitingUpdatedLock {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor_RunMonitoringLoop_WaitingUpdatedLock", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_RunMonitoringLoop_WokeUpMonitorWaiting {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor_RunMonitoringLoop_WokeUpMonitorWaiting", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_RunNodeMonitoringAsync_OperationCancelled {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor_RunNodeMonitoringAsync_OperationCancelled", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_RunNodeMonitoringAsync_StartNode {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor_RunNodeMonitoringAsync_StartNode", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_RunNodeMonitoringAsync_UnknownException {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor_RunNodeMonitoringAsync_UnknownException", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_UpdateTopologyCache_NotifyingLock {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor_UpdateTopologyCache_NotifyingLock", resourceCulture);
            }
        }
        
        internal static string ClusterTopologyMonitor_UpdateTopologyCache_TopologyUpdate {
            get {
                return ResourceManager.GetString("ClusterTopologyMonitor_UpdateTopologyCache_TopologyUpdate", resourceCulture);
            }
        }
        
        internal static string DbConnectionProvider_CreateDbConnection {
            get {
                return ResourceManager.GetString("DbConnectionProvider_CreateDbConnection", resourceCulture);
            }
        }
        
        internal static string DbConnectionProvider_GetHostSpecByStrategy_SelectedStrategy {
            get {
                return ResourceManager.GetString("DbConnectionProvider_GetHostSpecByStrategy_SelectedStrategy", resourceCulture);
            }
        }
        
        internal static string DefaultConnectionPlugin_Execute_ExecutingMethod {
            get {
                return ResourceManager.GetString("DefaultConnectionPlugin_Execute_ExecutingMethod", resourceCulture);
            }
        }
        
        internal static string DefaultConnectionPlugin_OpenInternal_ConnectionOpened {
            get {
                return ResourceManager.GetString("DefaultConnectionPlugin_OpenInternal_ConnectionOpened", resourceCulture);
            }
        }
        
        internal static string DialectProvider_GetDialectFromType_KnownDialect {
            get {
                return ResourceManager.GetString("DialectProvider_GetDialectFromType_KnownDialect", resourceCulture);
            }
        }
        
        internal static string DialectProvider_GetDialectFromType_UnknownDialect {
            get {
                return ResourceManager.GetString("DialectProvider_GetDialectFromType_UnknownDialect", resourceCulture);
            }
        }
        
        internal static string DialectProvider_GuessDialect_CacheDialect {
            get {
                return ResourceManager.GetString("DialectProvider_GuessDialect_CacheDialect", resourceCulture);
            }
        }
        
        internal static string DialectProvider_GuessDialect_ResultDialect {
            get {
                return ResourceManager.GetString("DialectProvider_GuessDialect_ResultDialect", resourceCulture);
            }
        }
        
        internal static string DialectProvider_UpdateDialectAsync_CurrentDialectConnectionType {
            get {
                return ResourceManager.GetString("DialectProvider_UpdateDialectAsync_CurrentDialectConnectionType", resourceCulture);
            }
        }
        
        internal static string DialectProvider_UpdateDialectAsync_CurrentDialectValid {
            get {
                return ResourceManager.GetString("DialectProvider_UpdateDialectAsync_CurrentDialectValid", resourceCulture);
            }
        }
        
        internal static string DialectProvider_UpdateDialectAsync_DialectMatch {
            get {
                return ResourceManager.GetString("DialectProvider_UpdateDialectAsync_DialectMatch", resourceCulture);
            }
        }
        
        internal static string DialectProvider_UpdateDialectAsync_ExistingDialect {
            get {
                return ResourceManager.GetString("DialectProvider_UpdateDialectAsync_ExistingDialect", resourceCulture);
            }
        }
        
        internal static string DialectProvider_UpdateDialectAsync_InvalidDialectTypes {
            get {
                return ResourceManager.GetString("DialectProvider_UpdateDialectAsync_InvalidDialectTypes", resourceCulture);
            }
        }
        
        internal static string DialectProvider_UpdateDialectAsync_NoMatchingDialect {
            get {
                return ResourceManager.GetString("DialectProvider_UpdateDialectAsync_NoMatchingDialect", resourceCulture);
            }
        }
        
        internal static string DialectProvider_UpdateDialectAsync_TestingCurrentDialect {
            get {
                return ResourceManager.GetString("DialectProvider_UpdateDialectAsync_TestingCurrentDialect", resourceCulture);
            }
        }
        
        internal static string DialectProvider_UpdateDialectAsync_TestingDialectCandidate {
            get {
                return ResourceManager.GetString("DialectProvider_UpdateDialectAsync_TestingDialectCandidate", resourceCulture);
            }
        }
        
        internal static string DialectProvider_UpdateDialectAsync_TestingDialects {
            get {
                return ResourceManager.GetString("DialectProvider_UpdateDialectAsync_TestingDialects", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitorConnectionContext_SetInactive_SettingContextInactive {
            get {
                return ResourceManager.GetString("EfmHostMonitorConnectionContext_SetInactive_SettingContextInactive", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitorService_OnMonitorEvicted_DisposingHostMonitor {
            get {
                return ResourceManager.GetString("EfmHostMonitorService_OnMonitorEvicted_DisposingHostMonitor", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitorService_StartMonitoring_NewContextCreated {
            get {
                return ResourceManager.GetString("EfmHostMonitorService_StartMonitoring_NewContextCreated", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitorService_StopMonitoring_AbortingUnhealthyConnection {
            get {
                return ResourceManager.GetString("EfmHostMonitorService_StopMonitoring_AbortingUnhealthyConnection", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitor_AbortConnection_Finished {
            get {
                return ResourceManager.GetString("EfmHostMonitor_AbortConnection_Finished", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitor_AbortConnection_Starting {
            get {
                return ResourceManager.GetString("EfmHostMonitor_AbortConnection_Starting", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitor_ActivatedMonitoring {
            get {
                return ResourceManager.GetString("EfmHostMonitor_ActivatedMonitoring", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitor_ActiveContextsException {
            get {
                return ResourceManager.GetString("EfmHostMonitor_ActiveContextsException", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitor_CheckConnectionStatusAsync_CommandTimeout {
            get {
                return ResourceManager.GetString("EfmHostMonitor_CheckConnectionStatusAsync_CommandTimeout", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitor_CheckConnectionStatusAsync_DisposingInvalidConnection {
            get {
                return ResourceManager.GetString("EfmHostMonitor_CheckConnectionStatusAsync_DisposingInvalidConnection", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitor_DeactivatedMonitoring {
            get {
                return ResourceManager.GetString("EfmHostMonitor_DeactivatedMonitoring", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitor_ErrorIdentifyingConnection {
            get {
                return ResourceManager.GetString("EfmHostMonitor_ErrorIdentifyingConnection", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitor_ExceptionAbortingConnection {
            get {
                return ResourceManager.GetString("EfmHostMonitor_ExceptionAbortingConnection", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitor_HostAlive {
            get {
                return ResourceManager.GetString("EfmHostMonitor_HostAlive", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitor_HostDead {
            get {
                return ResourceManager.GetString("EfmHostMonitor_HostDead", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitor_HostNotResponding {
            get {
                return ResourceManager.GetString("EfmHostMonitor_HostNotResponding", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitor_NewContextRun_AddingActiveContext {
            get {
                return ResourceManager.GetString("EfmHostMonitor_NewContextRun_AddingActiveContext", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitor_NewContextsException {
            get {
                return ResourceManager.GetString("EfmHostMonitor_NewContextsException", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitor_OpenedMonitoringConnection {
            get {
                return ResourceManager.GetString("EfmHostMonitor_OpenedMonitoringConnection", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitor_OpeningMonitoringConnection {
            get {
                return ResourceManager.GetString("EfmHostMonitor_OpeningMonitoringConnection", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitor_Run_AddingContextBack {
            get {
                return ResourceManager.GetString("EfmHostMonitor_Run_AddingContextBack", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitor_Run_AddingContextToTemp {
            get {
                return ResourceManager.GetString("EfmHostMonitor_Run_AddingContextToTemp", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitor_Run_CurrentActiveContextsCount {
            get {
                return ResourceManager.GetString("EfmHostMonitor_Run_CurrentActiveContextsCount", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitor_Run_DequeuedContext {
            get {
                return ResourceManager.GetString("EfmHostMonitor_Run_DequeuedContext", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitor_Run_NoActiveContextsSkipping {
            get {
                return ResourceManager.GetString("EfmHostMonitor_Run_NoActiveContextsSkipping", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitor_StartMonitoringWhenStopped {
            get {
                return ResourceManager.GetString("EfmHostMonitor_StartMonitoringWhenStopped", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitor_StartedMonitoringActiveContexts {
            get {
                return ResourceManager.GetString("EfmHostMonitor_StartedMonitoringActiveContexts", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitor_StartedPollingNewContexts {
            get {
                return ResourceManager.GetString("EfmHostMonitor_StartedPollingNewContexts", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitor_StoppedMonitoring {
            get {
                return ResourceManager.GetString("EfmHostMonitor_StoppedMonitoring", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitor_StoppedMonitoringActiveContexts {
            get {
                return ResourceManager.GetString("EfmHostMonitor_StoppedMonitoringActiveContexts", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitor_StoppedPollingNewContexts {
            get {
                return ResourceManager.GetString("EfmHostMonitor_StoppedPollingNewContexts", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitoringPlugin_Execute_DeactivatingMonitoring {
            get {
                return ResourceManager.GetString("EfmHostMonitoringPlugin_Execute_DeactivatingMonitoring", resourceCulture);
            }
        }
        
        internal static string EfmHostMonitoringPlugin_GetMonitoringHostSpec_ClusterEndpointIdentification {
            get {
                return ResourceManager.GetString("EfmHostMonitoringPlugin_GetMonitoringHostSpec_ClusterEndpointIdentification", resourceCulture);
            }
        }
        
        internal static string Error_CantCheckDialect {
            get {
                return ResourceManager.GetString("Error_CantCheckDialect", resourceCulture);
            }
        }
        
        internal static string Error_CantCheckDialect_ConnectionState {
            get {
                return ResourceManager.GetString("Error_CantCheckDialect_ConnectionState", resourceCulture);
            }
        }
        
        internal static string Error_CantLoadTargetConnectionType {
            get {
                return ResourceManager.GetString("Error_CantLoadTargetConnectionType", resourceCulture);
            }
        }
        
        internal static string Error_CannotUnwrap {
            get {
                return ResourceManager.GetString("Error_CannotUnwrap", resourceCulture);
            }
        }
        
        internal static string Error_ConnectionAlreadyOpen {
            get {
                return ResourceManager.GetString("Error_ConnectionAlreadyOpen", resourceCulture);
            }
        }
        
        internal static string Error_ConnectionIsClosed {
            get {
                return ResourceManager.GetString("Error_ConnectionIsClosed", resourceCulture);
            }
        }
        
        internal static string Error_ConnectionNotOpenWhenChecking {
            get {
                return ResourceManager.GetString("Error_ConnectionNotOpenWhenChecking", resourceCulture);
            }
        }
        
        internal static string Error_ConnectionStringHostListProviderNoSupport {
            get {
                return ResourceManager.GetString("Error_ConnectionStringHostListProviderNoSupport", resourceCulture);
            }
        }
        
        internal static string Error_ConnectionStringHostListProvider_GetClusterId {
            get {
                return ResourceManager.GetString("Error_ConnectionStringHostListProvider_GetClusterId", resourceCulture);
            }
        }
        
        internal static string Error_ConnectionStringHostListProvider_GetHostRoleAsync {
            get {
                return ResourceManager.GetString("Error_ConnectionStringHostListProvider_GetHostRoleAsync", resourceCulture);
            }
        }
        
        internal static string Error_ConnectionStringInvalid {
            get {
                return ResourceManager.GetString("Error_ConnectionStringInvalid", resourceCulture);
            }
        }
        
        internal static string Error_ConnectionStringMustBeSetBeforeInitialization {
            get {
                return ResourceManager.GetString("Error_ConnectionStringMustBeSetBeforeInitialization", resourceCulture);
            }
        }
        
        internal static string Error_ConnectionUrlMissing {
            get {
                return ResourceManager.GetString("Error_ConnectionUrlMissing", resourceCulture);
            }
        }
        
        internal static string Error_CouldNotCreateOrGetMonitor {
            get {
                return ResourceManager.GetString("Error_CouldNotCreateOrGetMonitor", resourceCulture);
            }
        }
        
        internal static string Error_CouldntIdentifyConnection {
            get {
                return ResourceManager.GetString("Error_CouldntIdentifyConnection", resourceCulture);
            }
        }
        
        internal static string Error_DisposingHostMonitor {
            get {
                return ResourceManager.GetString("Error_DisposingHostMonitor", resourceCulture);
            }
        }
        
        internal static string Error_DriverDoesNotSupportRequestedHostSelectionStrategy {
            get {
                return ResourceManager.GetString("Error_DriverDoesNotSupportRequestedHostSelectionStrategy", resourceCulture);
            }
        }
        
        internal static string Error_ExceptionConnectingToWriter {
            get {
                return ResourceManager.GetString("Error_ExceptionConnectingToWriter", resourceCulture);
            }
        }
        
        internal static string Error_ExceptionDuringMethodExecution {
            get {
                return ResourceManager.GetString("Error_ExceptionDuringMethodExecution", resourceCulture);
            }
        }
        
        internal static string Error_FailedConnection {
            get {
                return ResourceManager.GetString("Error_FailedConnection", resourceCulture);
            }
        }
        
        internal static string Error_FailedToConnectToHost {
            get {
                return ResourceManager.GetString("Error_FailedToConnectToHost", resourceCulture);
            }
        }
        
        internal static string Error_FailedToInstantiateCustomDialectType {
            get {
                return ResourceManager.GetString("Error_FailedToInstantiateCustomDialectType", resourceCulture);
            }
        }
        
        internal static string Error_FailedToInstantiateDialect {
            get {
                return ResourceManager.GetString("Error_FailedToInstantiateDialect", resourceCulture);
            }
        }
        
        internal static string Error_FailedToInstantiateDialectType {
            get {
                return ResourceManager.GetString("Error_FailedToInstantiateDialectType", resourceCulture);
            }
        }
        
        internal static string Error_FailoverPluginShouldNotReachHere {
            get {
                return ResourceManager.GetString("Error_FailoverPluginShouldNotReachHere", resourceCulture);
            }
        }
        
        internal static string Error_FailoverReaderTimeout {
            get {
                return ResourceManager.GetString("Error_FailoverReaderTimeout", resourceCulture);
            }
        }
        
        internal static string Error_FailoverSuccessActiveConnectionChanged {
            get {
                return ResourceManager.GetString("Error_FailoverSuccessActiveConnectionChanged", resourceCulture);
            }
        }
        
        internal static string Error_FunctionShouldNotBeCalled {
            get {
                return ResourceManager.GetString("Error_FunctionShouldNotBeCalled", resourceCulture);
            }
        }
        
        internal static string Error_HostNullEmpty {
            get {
                return ResourceManager.GetString("Error_HostNullEmpty", resourceCulture);
            }
        }
        
        internal static string Error_InvalidConnection {
            get {
                return ResourceManager.GetString("Error_InvalidConnection", resourceCulture);
            }
        }
        
        internal static string Error_InvalidCustomRdsProxyUrl {
            get {
                return ResourceManager.GetString("Error_InvalidCustomRdsProxyUrl", resourceCulture);
            }
        }
        
        internal static string Error_InvalidDialectType {
            get {
                return ResourceManager.GetString("Error_InvalidDialectType", resourceCulture);
            }
        }
        
        internal static string Error_InvalidHostPattern {
            get {
                return ResourceManager.GetString("Error_InvalidHostPattern", resourceCulture);
            }
        }
        
        internal static string Error_InvalidHostRole {
            get {
                return ResourceManager.GetString("Error_InvalidHostRole", resourceCulture);
            }
        }
        
        internal static string Error_InvalidOpenConnectionException {
            get {
                return ResourceManager.GetString("Error_InvalidOpenConnectionException", resourceCulture);
            }
        }
        
        internal static string Error_InvalidQuery {
            get {
                return ResourceManager.GetString("Error_InvalidQuery", resourceCulture);
            }
        }
        
        internal static string Error_InvalidOperation {
            get {
                return ResourceManager.GetString("Error_InvalidOperation", resourceCulture);
            }
        }
        
        internal static string Error_InvalidRdsProxyUrl {
            get {
                return ResourceManager.GetString("Error_InvalidRdsProxyUrl", resourceCulture);
            }
        }
        
        internal static string Error_InvalidRoundRobinPairEmpty {
            get {
                return ResourceManager.GetString("Error_InvalidRoundRobinPairEmpty", resourceCulture);
            }
        }
        
        internal static string Error_InvalidRoundRobinPairFormat {
            get {
                return ResourceManager.GetString("Error_InvalidRoundRobinPairFormat", resourceCulture);
            }
        }
        
        internal static string Error_InvalidRoundRobinValue {
            get {
                return ResourceManager.GetString("Error_InvalidRoundRobinValue", resourceCulture);
            }
        }
        
        internal static string Error_InvalidTopology_NoWriterInstance {
            get {
                return ResourceManager.GetString("Error_InvalidTopology_NoWriterInstance", resourceCulture);
            }
        }
        
        internal static string Error_NewWriterNotInAllowedHostsList {
            get {
                return ResourceManager.GetString("Error_NewWriterNotInAllowedHostsList", resourceCulture);
            }
        }
        
        internal static string Error_NoDialectFoundForConnectionType {
            get {
                return ResourceManager.GetString("Error_NoDialectFoundForConnectionType", resourceCulture);
            }
        }
        
        internal static string Error_NoHostsMatching {
            get {
                return ResourceManager.GetString("Error_NoHostsMatching", resourceCulture);
            }
        }
        
        internal static string Error_NoWriterHostFoundInUpdatedTopology {
            get {
                return ResourceManager.GetString("Error_NoWriterHostFoundInUpdatedTopology", resourceCulture);
            }
        }
        
        internal static string Error_NotAwsWrapperConnection {
            get {
                return ResourceManager.GetString("Error_NotAwsWrapperConnection", resourceCulture);
            }
        }
        
        internal static string Error_NotFoundInConnectionString {
            get {
                return ResourceManager.GetString("Error_NotFoundInConnectionString", resourceCulture);
            }
        }
        
        internal static string Error_NotImplementedDbCommand {
            get {
                return ResourceManager.GetString("Error_NotImplementedDbCommand", resourceCulture);
            }
        }
        
        internal static string Error_ObtainingConnectionHostId {
            get {
                return ResourceManager.GetString("Error_ObtainingConnectionHostId", resourceCulture);
            }
        }
        
        internal static string Error_ProcessingAdoNetCall {
            get {
                return ResourceManager.GetString("Error_ProcessingAdoNetCall", resourceCulture);
            }
        }
        
        internal static string Error_ProvidedCommandNotAwsWrapperCommand {
            get {
                return ResourceManager.GetString("Error_ProvidedCommandNotAwsWrapperCommand", resourceCulture);
            }
        }
        
        internal static string Error_ProvidedConnectionNotAwsWrapperConnection {
            get {
                return ResourceManager.GetString("Error_ProvidedConnectionNotAwsWrapperConnection", resourceCulture);
            }
        }
        
        internal static string Error_ProvidedDbTransactionNotAwsWrapperTransaction {
            get {
                return ResourceManager.GetString("Error_ProvidedDbTransactionNotAwsWrapperTransaction", resourceCulture);
            }
        }
        
        internal static string Error_ProvidedTransactionNotAwsWrapperTransaction {
            get {
                return ResourceManager.GetString("Error_ProvidedTransactionNotAwsWrapperTransaction", resourceCulture);
            }
        }
        
        internal static string Error_ProvidedTypeDoesntImplementIDbCommand {
            get {
                return ResourceManager.GetString("Error_ProvidedTypeDoesntImplementIDbCommand", resourceCulture);
            }
        }
        
        internal static string Error_RequiredIBlockingHostListProvider {
            get {
                return ResourceManager.GetString("Error_RequiredIBlockingHostListProvider", resourceCulture);
            }
        }
        
        internal static string Error_ShouldNotBeCalled {
            get {
                return ResourceManager.GetString("Error_ShouldNotBeCalled", resourceCulture);
            }
        }
        
        internal static string Error_ShouldNotGetHere {
            get {
                return ResourceManager.GetString("Error_ShouldNotGetHere", resourceCulture);
            }
        }
        
        internal static string Error_TargetConnectionTypeNotFound {
            get {
                return ResourceManager.GetString("Error_TargetConnectionTypeNotFound", resourceCulture);
            }
        }
        
        internal static string Error_TestingCurrentDialect {
            get {
                return ResourceManager.GetString("Error_TestingCurrentDialect", resourceCulture);
            }
        }
        
        internal static string Error_TestingDialectCandidates {
            get {
                return ResourceManager.GetString("Error_TestingDialectCandidates", resourceCulture);
            }
        }
        
        internal static string Error_ThrownErrorIgnoredFindingMonitoringConnection {
            get {
                return ResourceManager.GetString("Error_ThrownErrorIgnoredFindingMonitoringConnection", resourceCulture);
            }
        }
        
        internal static string Error_TransactionResolutionUnknown {
            get {
                return ResourceManager.GetString("Error_TransactionResolutionUnknown", resourceCulture);
            }
        }
        
        internal static string Error_UnsupportedDialectOrDatabase {
            get {
                return ResourceManager.GetString("Error_UnsupportedDialectOrDatabase", resourceCulture);
            }
        }
        
        internal static string Error_UnableToCreateConnection {
            get {
                return ResourceManager.GetString("Error_UnableToCreateConnection", resourceCulture);
            }
        }
        
        internal static string Error_UnableToEstablishConnection {
            get {
                return ResourceManager.GetString("Error_UnableToEstablishConnection", resourceCulture);
            }
        }
        
        internal static string Error_UnableToEstablishValidConnectionAfterMultipleAttempts {
            get {
                return ResourceManager.GetString("Error_UnableToEstablishValidConnectionAfterMultipleAttempts", resourceCulture);
            }
        }
        
        internal static string Error_UnableToFindValidDialectType {
            get {
                return ResourceManager.GetString("Error_UnableToFindValidDialectType", resourceCulture);
            }
        }
        
        internal static string Error_UnableToIdentifyConnectionAndGatherMonitoringHostSpec {
            get {
                return ResourceManager.GetString("Error_UnableToIdentifyConnectionAndGatherMonitoringHostSpec", resourceCulture);
            }
        }
        
        internal static string Error_UnableToLoadAwsPluginFromAssembly {
            get {
                return ResourceManager.GetString("Error_UnableToLoadAwsPluginFromAssembly", resourceCulture);
            }
        }
        
        internal static string Error_UnableToLoadPlugin {
            get {
                return ResourceManager.GetString("Error_UnableToLoadPlugin", resourceCulture);
            }
        }
        
        internal static string Error_UnexpectedRoleForWriterCandidate {
            get {
                return ResourceManager.GetString("Error_UnexpectedRoleForWriterCandidate", resourceCulture);
            }
        }
        
        internal static string Error_UnknownAwsPluginCode {
            get {
                return ResourceManager.GetString("Error_UnknownAwsPluginCode", resourceCulture);
            }
        }
        
        internal static string Error_UnknownPluginCode {
            get {
                return ResourceManager.GetString("Error_UnknownPluginCode", resourceCulture);
            }
        }
        
        internal static string ExecutionTimePlugin_Execute_ExecutionTime {
            get {
                return ResourceManager.GetString("ExecutionTimePlugin_Execute_ExecutionTime", resourceCulture);
            }
        }
        
        internal static string FailoverPlugin_DealWithOriginalExceptionAsync_MarkingHostUnavailable {
            get {
                return ResourceManager.GetString("FailoverPlugin_DealWithOriginalExceptionAsync_MarkingHostUnavailable", resourceCulture);
            }
        }
        
        internal static string FailoverPlugin_DealWithOriginalExceptionAsync_ProcessingException {
            get {
                return ResourceManager.GetString("FailoverPlugin_DealWithOriginalExceptionAsync_ProcessingException", resourceCulture);
            }
        }
        
        internal static string FailoverPlugin_Execute_CurrentConnectionState {
            get {
                return ResourceManager.GetString("FailoverPlugin_Execute_CurrentConnectionState", resourceCulture);
            }
        }
        
        internal static string FailoverPlugin_Execute_ExecuteCalled {
            get {
                return ResourceManager.GetString("FailoverPlugin_Execute_ExecuteCalled", resourceCulture);
            }
        }
        
        internal static string FailoverPlugin_FailoverAsync_InitiatingFailover {
            get {
                return ResourceManager.GetString("FailoverPlugin_FailoverAsync_InitiatingFailover", resourceCulture);
            }
        }
        
        internal static string FailoverPlugin_FailoverReaderAsync_ReaderFailoverSuccessful {
            get {
                return ResourceManager.GetString("FailoverPlugin_FailoverReaderAsync_ReaderFailoverSuccessful", resourceCulture);
            }
        }
        
        internal static string FailoverPlugin_FailoverReaderAsync_SetNewConnection {
            get {
                return ResourceManager.GetString("FailoverPlugin_FailoverReaderAsync_SetNewConnection", resourceCulture);
            }
        }
        
        internal static string FailoverPlugin_FailoverReaderAsync_StartingReaderFailover {
            get {
                return ResourceManager.GetString("FailoverPlugin_FailoverReaderAsync_StartingReaderFailover", resourceCulture);
            }
        }
        
        internal static string FailoverPlugin_FailoverWriterAsync_SetNewConnection {
            get {
                return ResourceManager.GetString("FailoverPlugin_FailoverWriterAsync_SetNewConnection", resourceCulture);
            }
        }
        
        internal static string FailoverPlugin_GetReaderFailoverConnectionAsync_ErrorSelectingReaderHost {
            get {
                return ResourceManager.GetString("FailoverPlugin_GetReaderFailoverConnectionAsync_ErrorSelectingReaderHost", resourceCulture);
            }
        }
        
        internal static string FailoverPlugin_GetReaderFailoverConnectionAsync_ExceptionGettingReaderCandidate {
            get {
                return ResourceManager.GetString("FailoverPlugin_GetReaderFailoverConnectionAsync_ExceptionGettingReaderCandidate", resourceCulture);
            }
        }
        
        internal static string FailoverPlugin_GetReaderFailoverConnectionAsync_FailedToConnectToHost {
            get {
                return ResourceManager.GetString("FailoverPlugin_GetReaderFailoverConnectionAsync_FailedToConnectToHost", resourceCulture);
            }
        }
        
        internal static string FailoverPlugin_GetReaderFailoverConnectionAsync_TryingOriginalWriter {
            get {
                return ResourceManager.GetString("FailoverPlugin_GetReaderFailoverConnectionAsync_TryingOriginalWriter", resourceCulture);
            }
        }
        
        internal static string FailoverPlugin_GetReaderFailoverConnectionAsync_UnableToDetermineHostRole {
            get {
                return ResourceManager.GetString("FailoverPlugin_GetReaderFailoverConnectionAsync_UnableToDetermineHostRole", resourceCulture);
            }
        }
        
        internal static string FailoverPlugin_GetReaderFailoverConnectionAsync_UnableToDetermineOriginalWriterRole {
            get {
                return ResourceManager.GetString("FailoverPlugin_GetReaderFailoverConnectionAsync_UnableToDetermineOriginalWriterRo" +
                        "le", resourceCulture);
            }
        }
        
        internal static string FailoverPlugin_InvalidInvocationOnClosedConnection_AttemptingNewConnection {
            get {
                return ResourceManager.GetString("FailoverPlugin_InvalidInvocationOnClosedConnection_AttemptingNewConnection", resourceCulture);
            }
        }
        
        internal static string FailoverPlugin_InvalidInvocationOnClosedConnection_Called {
            get {
                return ResourceManager.GetString("FailoverPlugin_InvalidInvocationOnClosedConnection_Called", resourceCulture);
            }
        }
        
        internal static string FailoverPlugin_InvalidInvocationOnClosedConnection_CurrentConnection {
            get {
                return ResourceManager.GetString("FailoverPlugin_InvalidInvocationOnClosedConnection_CurrentConnection", resourceCulture);
            }
        }
        
        internal static string FailoverPlugin_InvalidateCurrentConnectionAsync_ConnectionClosed {
            get {
                return ResourceManager.GetString("FailoverPlugin_InvalidateCurrentConnectionAsync_ConnectionClosed", resourceCulture);
            }
        }
        
        internal static string FailoverPlugin_InvalidateCurrentConnectionAsync_ErrorDisposingConnection {
            get {
                return ResourceManager.GetString("FailoverPlugin_InvalidateCurrentConnectionAsync_ErrorDisposingConnection", resourceCulture);
            }
        }
        
        internal static string FailoverPlugin_InvalidateCurrentConnectionAsync_InvalidatingConnection {
            get {
                return ResourceManager.GetString("FailoverPlugin_InvalidateCurrentConnectionAsync_InvalidatingConnection", resourceCulture);
            }
        }
        
        internal static string FailoverPlugin_OpenConnection_ReturningConnection {
            get {
                return ResourceManager.GetString("FailoverPlugin_OpenConnection_ReturningConnection", resourceCulture);
            }
        }
        
        internal static string FailoverPlugin_PickNewConnectionAsync_ConnectionClosedExplicitly {
            get {
                return ResourceManager.GetString("FailoverPlugin_PickNewConnectionAsync_ConnectionClosedExplicitly", resourceCulture);
            }
        }
        
        internal static string FailoverPlugin_PickNewConnectionAsync_PickingNewConnection {
            get {
                return ResourceManager.GetString("FailoverPlugin_PickNewConnectionAsync_PickingNewConnection", resourceCulture);
            }
        }
        
        internal static string FailoverPlugin_ShouldExceptionTriggerConnectionSwitch_FailoverDisabled {
            get {
                return ResourceManager.GetString("FailoverPlugin_ShouldExceptionTriggerConnectionSwitch_FailoverDisabled", resourceCulture);
            }
        }
        
        internal static string FailoverPlugin_ShouldExceptionTriggerConnectionSwitch_ThreadInterrupted {
            get {
                return ResourceManager.GetString("FailoverPlugin_ShouldExceptionTriggerConnectionSwitch_ThreadInterrupted", resourceCulture);
            }
        }
        
        internal static string FailoverPlugin_ThrowFailoverSuccessException_CurrentConnectionAfterFailover {
            get {
                return ResourceManager.GetString("FailoverPlugin_ThrowFailoverSuccessException_CurrentConnectionAfterFailover", resourceCulture);
            }
        }
        
        internal static string FailoverPlugin_ThrowFailoverSuccessException_FailoverSucceeded {
            get {
                return ResourceManager.GetString("FailoverPlugin_ThrowFailoverSuccessException_FailoverSucceeded", resourceCulture);
            }
        }
        
        internal static string MonitoringRdsHostListProvider_ClusterIdChanged {
            get {
                return ResourceManager.GetString("MonitoringRdsHostListProvider_ClusterIdChanged", resourceCulture);
            }
        }
        
        internal static string MonitoringRdsHostListProvider_InitMonitor {
            get {
                return ResourceManager.GetString("MonitoringRdsHostListProvider_InitMonitor", resourceCulture);
            }
        }
        
        internal static string MonitoringRdsHostListProvider_OnMonitorEvicted_Disposing {
            get {
                return ResourceManager.GetString("MonitoringRdsHostListProvider_OnMonitorEvicted_Disposing", resourceCulture);
            }
        }
        
        internal static string MonitoringRdsHostListProvider_OnMonitorEvicted_Error {
            get {
                return ResourceManager.GetString("MonitoringRdsHostListProvider_OnMonitorEvicted_Error", resourceCulture);
            }
        }
        
        internal static string MonitoringRdsHostListProvider_QueryForTopologyAsync_TimedOut {
            get {
                return ResourceManager.GetString("MonitoringRdsHostListProvider_QueryForTopologyAsync_TimedOut", resourceCulture);
            }
        }
        
        internal static string MonitoringRdsHostListProvider_TransferCachedTopology {
            get {
                return ResourceManager.GetString("MonitoringRdsHostListProvider_TransferCachedTopology", resourceCulture);
            }
        }
        
        internal static string MonitoringRdsHostListProvider_TransferExistingMonitor {
            get {
                return ResourceManager.GetString("MonitoringRdsHostListProvider_TransferExistingMonitor", resourceCulture);
            }
        }
        
        internal static string MultiAzClusterTopologyMonitor_GetSuggestedWriterNodeIdAsync_Error {
            get {
                return ResourceManager.GetString("MultiAzClusterTopologyMonitor_GetSuggestedWriterNodeIdAsync_Error", resourceCulture);
            }
        }
        
        internal static string MultiAzClusterTopologyMonitor_GetWriterNodeIdAsync_Error {
            get {
                return ResourceManager.GetString("MultiAzClusterTopologyMonitor_GetWriterNodeIdAsync_Error", resourceCulture);
            }
        }
        
        internal static string MySqlExceptionHandler_IsNetworkException_CurrentException {
            get {
                return ResourceManager.GetString("MySqlExceptionHandler_IsNetworkException_CurrentException", resourceCulture);
            }
        }
        
        internal static string MySqlExceptionHandler_IsNetworkException_CurrentNetworkException {
            get {
                return ResourceManager.GetString("MySqlExceptionHandler_IsNetworkException_CurrentNetworkException", resourceCulture);
            }
        }
        
        internal static string MySqlExceptionHandler_IsNetworkException_InnerException {
            get {
                return ResourceManager.GetString("MySqlExceptionHandler_IsNetworkException_InnerException", resourceCulture);
            }
        }
        
        internal static string MySqlExceptionHandler_IsNetworkException_InvalidNetworkException {
            get {
                return ResourceManager.GetString("MySqlExceptionHandler_IsNetworkException_InvalidNetworkException", resourceCulture);
            }
        }
        
        internal static string NodeMonitoringTask_DetectedWriter {
            get {
                return ResourceManager.GetString("NodeMonitoringTask_DetectedWriter", resourceCulture);
            }
        }
        
        internal static string NodeMonitoringTask_ThreadCompleted {
            get {
                return ResourceManager.GetString("NodeMonitoringTask_ThreadCompleted", resourceCulture);
            }
        }
        
        internal static string NodeMonitoringTask_WriterNodeChanged {
            get {
                return ResourceManager.GetString("NodeMonitoringTask_WriterNodeChanged", resourceCulture);
            }
        }
        
        internal static string PluginService_ErrorClosingOldConnection {
            get {
                return ResourceManager.GetString("PluginService.ErrorClosingOldConnection", resourceCulture);
            }
        }
        
        internal static string PluginService_ForceRefreshHostListAsync_Completed {
            get {
                return ResourceManager.GetString("PluginService_ForceRefreshHostListAsync_Completed", resourceCulture);
            }
        }
        
        internal static string PluginService_ForceRefreshHostListAsync_CompletedWithConnection {
            get {
                return ResourceManager.GetString("PluginService_ForceRefreshHostListAsync_CompletedWithConnection", resourceCulture);
            }
        }
        
        internal static string PluginService_ForceRefreshHostListAsync_TimeoutException {
            get {
                return ResourceManager.GetString("PluginService_ForceRefreshHostListAsync_TimeoutException", resourceCulture);
            }
        }
        
        internal static string PluginService_RefreshHostListAsync_Completed {
            get {
                return ResourceManager.GetString("PluginService_RefreshHostListAsync_Completed", resourceCulture);
            }
        }
        
        internal static string PluginService_RefreshHostListAsync_CompletedWithConnection {
            get {
                return ResourceManager.GetString("PluginService_RefreshHostListAsync_CompletedWithConnection", resourceCulture);
            }
        }
        
        internal static string PluginService_SetAvailability_HostAvailabilityChanged {
            get {
                return ResourceManager.GetString("PluginService_SetAvailability_HostAvailabilityChanged", resourceCulture);
            }
        }
        
        internal static string PluginService_SetAvailability_NoChanges {
            get {
                return ResourceManager.GetString("PluginService_SetAvailability_NoChanges", resourceCulture);
            }
        }
        
        internal static string PluginService_SetCurrentConnection_Completed {
            get {
                return ResourceManager.GetString("PluginService_SetCurrentConnection_Completed", resourceCulture);
            }
        }
        
        internal static string PluginService_SetCurrentConnection_NewConnectionDetails {
            get {
                return ResourceManager.GetString("PluginService_SetCurrentConnection_NewConnectionDetails", resourceCulture);
            }
        }
        
        internal static string PluginService_SetCurrentConnection_NewConnectionSet {
            get {
                return ResourceManager.GetString("PluginService_SetCurrentConnection_NewConnectionSet", resourceCulture);
            }
        }
        
        internal static string PluginService_SetCurrentConnection_OldConnectionDisposed {
            get {
                return ResourceManager.GetString("PluginService_SetCurrentConnection_OldConnectionDisposed", resourceCulture);
            }
        }
        
        internal static string PluginService_SetCurrentConnection_SameReference {
            get {
                return ResourceManager.GetString("PluginService_SetCurrentConnection_SameReference", resourceCulture);
            }
        }
        
        internal static string PluginService_UpdateDialectAsync_DialectUpdated {
            get {
                return ResourceManager.GetString("PluginService_UpdateDialectAsync_DialectUpdated", resourceCulture);
            }
        }
        
        internal static string RdsHostListProvider_GetTopologyAsync_CacheLookup {
            get {
                return ResourceManager.GetString("RdsHostListProvider_GetTopologyAsync_CacheLookup", resourceCulture);
            }
        }
        
        internal static string RdsHostListProvider_GetTopologyAsync_CachedNewTopology {
            get {
                return ResourceManager.GetString("RdsHostListProvider_GetTopologyAsync_CachedNewTopology", resourceCulture);
            }
        }
        
        internal static string RdsHostListProvider_GetTopologyAsync_CachedTopology {
            get {
                return ResourceManager.GetString("RdsHostListProvider_GetTopologyAsync_CachedTopology", resourceCulture);
            }
        }
        
        internal static string RdsHostListProvider_GetTopologyAsync_ClusterIdChanged {
            get {
                return ResourceManager.GetString("RdsHostListProvider_GetTopologyAsync_ClusterIdChanged", resourceCulture);
            }
        }
        
        internal static string RdsHostListProvider_GetTopologyAsync_ConnectionUnavailable {
            get {
                return ResourceManager.GetString("RdsHostListProvider_GetTopologyAsync_ConnectionUnavailable", resourceCulture);
            }
        }
        
        internal static string RdsHostListProvider_GetTopologyAsync_FallbackTopology {
            get {
                return ResourceManager.GetString("RdsHostListProvider_GetTopologyAsync_FallbackTopology", resourceCulture);
            }
        }
        
        internal static string RdsHostListProvider_GetTopologyAsync_FallingBackToInitialHost {
            get {
                return ResourceManager.GetString("RdsHostListProvider_GetTopologyAsync_FallingBackToInitialHost", resourceCulture);
            }
        }
        
        internal static string RdsHostListProvider_GetTopologyAsync_NewTopology {
            get {
                return ResourceManager.GetString("RdsHostListProvider_GetTopologyAsync_NewTopology", resourceCulture);
            }
        }
        
        internal static string RdsHostListProvider_Init_ClusterInstanceTemplate {
            get {
                return ResourceManager.GetString("RdsHostListProvider_Init_ClusterInstanceTemplate", resourceCulture);
            }
        }
        
        internal static string RdsHostListProvider_Init_InitialHostCount {
            get {
                return ResourceManager.GetString("RdsHostListProvider_Init_InitialHostCount", resourceCulture);
            }
        }
        
        internal static string RdsHostListProvider_Init_InitialHostsAndCluster {
            get {
                return ResourceManager.GetString("RdsHostListProvider_Init_InitialHostsAndCluster", resourceCulture);
            }
        }
        
        internal static string RdsHostListProvider_QueryForTopologyAsync {
            get {
                return ResourceManager.GetString("RdsHostListProvider_QueryForTopologyAsync", resourceCulture);
            }
        }
        
        internal static string RdsMultiAzDbClusterListProvider_ProcessWriterNodeId_NoWriterNodesFound {
            get {
                return ResourceManager.GetString("RdsMultiAzDbClusterListProvider_ProcessWriterNodeId_NoWriterNodesFound", resourceCulture);
            }
        }
        
        internal static string RdsMultiAzDbClusterMySqlDialect_IsDialect_AsyncReader {
            get {
                return ResourceManager.GetString("RdsMultiAzDbClusterMySqlDialect_IsDialect_AsyncReader", resourceCulture);
            }
        }
        
        internal static string RdsMultiAzDbClusterPgDialect_IsDialect {
            get {
                return ResourceManager.GetString("RdsMultiAzDbClusterPgDialect_IsDialect", resourceCulture);
            }
        }
        
        internal static string RdsMultiAzDbClusterPgDialect_IsDialect_InvalidRdsTools {
            get {
                return ResourceManager.GetString("RdsMultiAzDbClusterPgDialect_IsDialect_InvalidRdsTools", resourceCulture);
            }
        }
        
        internal static string ReadWriteSplittingPlugin_SetReadOnlyOnClosedConnection {
            get {
                return ResourceManager.GetString("ReadWriteSplittingPlugin_SetReadOnlyOnClosedConnection", resourceCulture);
            }
        }
        
        internal static string ReadWriteSplittingPlugin_EmptyHostList {
            get {
                return ResourceManager.GetString("ReadWriteSplittingPlugin_EmptyHostList", resourceCulture);
            }
        }
        
        internal static string ReadWriteSplittingPlugin_ErrorSwitchingToReader {
            get {
                return ResourceManager.GetString("ReadWriteSplittingPlugin_ErrorSwitchingToReader", resourceCulture);
            }
        }
        
        internal static string ReadWriteSplittingPlugin_FallbackToWriter {
            get {
                return ResourceManager.GetString("ReadWriteSplittingPlugin_FallbackToWriter", resourceCulture);
            }
        }
        
        internal static string ReadWriteSplittingPlugin_SetReadOnlyFalseInTransaction {
            get {
                return ResourceManager.GetString("ReadWriteSplittingPlugin_SetReadOnlyFalseInTransaction", resourceCulture);
            }
        }
        
        internal static string ReadWriteSplittingPlugin_ErrorSwitchingToWriter {
            get {
                return ResourceManager.GetString("ReadWriteSplittingPlugin_ErrorSwitchingToWriter", resourceCulture);
            }
        }
        
        internal static string ReadWriteSplittingPlugin_NoWriterFound {
            get {
                return ResourceManager.GetString("ReadWriteSplittingPlugin_NoWriterFound", resourceCulture);
            }
        }
        
        internal static string ReadWriteSplittingPlugin_SwitchedFromReaderToWriter {
            get {
                return ResourceManager.GetString("ReadWriteSplittingPlugin_SwitchedFromReaderToWriter", resourceCulture);
            }
        }
        
        internal static string ReadWriteSplittingPlugin_SetWriterConnection {
            get {
                return ResourceManager.GetString("ReadWriteSplittingPlugin_SetWriterConnection", resourceCulture);
            }
        }
        
        internal static string ReadWriteSplittingPlugin_SettingCurrentConnection {
            get {
                return ResourceManager.GetString("ReadWriteSplittingPlugin_SettingCurrentConnection", resourceCulture);
            }
        }
        
        internal static string ReadWriteSplittingPlugin_PreviousReaderNotAllowed {
            get {
                return ResourceManager.GetString("ReadWriteSplittingPlugin_PreviousReaderNotAllowed", resourceCulture);
            }
        }
        
        internal static string ReadWriteSplittingPlugin_NoReadersFound {
            get {
                return ResourceManager.GetString("ReadWriteSplittingPlugin_NoReadersFound", resourceCulture);
            }
        }
        
        internal static string ReadWriteSplittingPlugin_FailedToConnectToReader {
            get {
                return ResourceManager.GetString("ReadWriteSplittingPlugin_FailedToConnectToReader", resourceCulture);
            }
        }
        
        internal static string ReadWriteSplittingPlugin_NoReadersAvailable {
            get {
                return ResourceManager.GetString("ReadWriteSplittingPlugin_NoReadersAvailable", resourceCulture);
            }
        }
        
        internal static string ReadWriteSplittingPlugin_SuccessfullyConnectedToReader {
            get {
                return ResourceManager.GetString("ReadWriteSplittingPlugin_SuccessfullyConnectedToReader", resourceCulture);
            }
        }
        
        internal static string ReadWriteSplittingPlugin_ExceptionWhileExecutingCommand {
            get {
                return ResourceManager.GetString("ReadWriteSplittingPlugin_ExceptionWhileExecutingCommand", resourceCulture);
            }
        }
        
        internal static string ConnectTimePlugin_ConnectTime {
            get {
                return ResourceManager.GetString("ConnectTimePlugin_ConnectTime", resourceCulture);
            }
        }
        
        internal static string CustomEndpointPlugin_ConnectionRequestToCustomEndpoint {
            get {
                return ResourceManager.GetString("CustomEndpointPlugin_ConnectionRequestToCustomEndpoint", resourceCulture);
            }
        }
        
        internal static string CustomEndpointPlugin_ErrorParsingEndpointIdentifier {
            get {
                return ResourceManager.GetString("CustomEndpointPlugin_ErrorParsingEndpointIdentifier", resourceCulture);
            }
        }
        
        internal static string CustomEndpointPlugin_UnableToDetermineRegion {
            get {
                return ResourceManager.GetString("CustomEndpointPlugin_UnableToDetermineRegion", resourceCulture);
            }
        }
        
        internal static string CustomEndpointPlugin_OnMonitorEvicted_Disposing {
            get {
                return ResourceManager.GetString("CustomEndpointPlugin_OnMonitorEvicted_Disposing", resourceCulture);
            }
        }
        
        internal static string Error_DisposingCustomEndpointMonitor {
            get {
                return ResourceManager.GetString("Error_DisposingCustomEndpointMonitor", resourceCulture);
            }
        }
        
        internal static string CustomEndpointPlugin_WaitingForCustomEndpointInfo {
            get {
                return ResourceManager.GetString("CustomEndpointPlugin_WaitingForCustomEndpointInfo", resourceCulture);
            }
        }
        
        internal static string CustomEndpointPlugin_InterruptedThread {
            get {
                return ResourceManager.GetString("CustomEndpointPlugin_InterruptedThread", resourceCulture);
            }
        }
        
        internal static string CustomEndpointPlugin_TimedOutWaitingForCustomEndpointInfo {
            get {
                return ResourceManager.GetString("CustomEndpointPlugin_TimedOutWaitingForCustomEndpointInfo", resourceCulture);
            }
        }
        
        internal static string CustomEndpointPlugin_ErrorCreatingMonitor {
            get {
                return ResourceManager.GetString("CustomEndpointPlugin_ErrorCreatingMonitor", resourceCulture);
            }
        }
        
        internal static string CustomEndpointPlugin_CloseMonitors {
            get {
                return ResourceManager.GetString("CustomEndpointPlugin_CloseMonitors", resourceCulture);
            }
        }
        
        internal static string CustomEndpointMonitorImpl_StartingMonitor {
            get {
                return ResourceManager.GetString("CustomEndpointMonitorImpl_StartingMonitor", resourceCulture);
            }
        }
        
        internal static string CustomEndpointMonitorImpl_UnexpectedNumberOfEndpoints {
            get {
                return ResourceManager.GetString("CustomEndpointMonitorImpl_UnexpectedNumberOfEndpoints", resourceCulture);
            }
        }
        
        internal static string CustomEndpointMonitorImpl_DetectedChangeInCustomEndpointInfo {
            get {
                return ResourceManager.GetString("CustomEndpointMonitorImpl_DetectedChangeInCustomEndpointInfo", resourceCulture);
            }
        }
        
        internal static string CustomEndpointMonitorImpl_Exception {
            get {
                return ResourceManager.GetString("CustomEndpointMonitorImpl_Exception", resourceCulture);
            }
        }
        
        internal static string CustomEndpointMonitorImpl_Interrupted {
            get {
                return ResourceManager.GetString("CustomEndpointMonitorImpl_Interrupted", resourceCulture);
            }
        }
        
        internal static string CustomEndpointMonitorImpl_StoppedMonitor {
            get {
                return ResourceManager.GetString("CustomEndpointMonitorImpl_StoppedMonitor", resourceCulture);
            }
        }
        
        internal static string CustomEndpointMonitorImpl_StoppingMonitor {
            get {
                return ResourceManager.GetString("CustomEndpointMonitorImpl_StoppingMonitor", resourceCulture);
            }
        }
        
        internal static string CustomEndpointMonitorImpl_MonitorTerminationTimeout {
            get {
                return ResourceManager.GetString("CustomEndpointMonitorImpl_MonitorTerminationTimeout", resourceCulture);
            }
        }
        
        internal static string CustomEndpointMonitorImpl_InterruptedWhileTerminating {
            get {
                return ResourceManager.GetString("CustomEndpointMonitorImpl_InterruptedWhileTerminating", resourceCulture);
            }
        }
        
        internal static string CustomEndpointMonitorImpl_ClearCache {
            get {
                return ResourceManager.GetString("CustomEndpointMonitorImpl_ClearCache", resourceCulture);
            }
        }
        
        internal static string CustomEndpointPluginFactory_AwsSdkNotInClasspath {
            get {
                return ResourceManager.GetString("CustomEndpointPluginFactory_AwsSdkNotInClasspath", resourceCulture);
            }
        }
        
        internal static string LimitlessRouterMonitor_Dispose_DidNotStopWithinSeconds {
            get {
                return ResourceManager.GetString("LimitlessRouterMonitor_Dispose_DidNotStopWithinSeconds", resourceCulture);
            }
        }
        
        internal static string LimitlessRouterMonitor_Dispose_ErrorWaitingForTask {
            get {
                return ResourceManager.GetString("LimitlessRouterMonitor_Dispose_ErrorWaitingForTask", resourceCulture);
            }
        }
        
        internal static string LimitlessRouterMonitor_Dispose_ThreadStopped {
            get {
                return ResourceManager.GetString("LimitlessRouterMonitor_Dispose_ThreadStopped", resourceCulture);
            }
        }
        
        internal static string LimitlessRouterMonitor_OpenConnection_Opened {
            get {
                return ResourceManager.GetString("LimitlessRouterMonitor_OpenConnection_Opened", resourceCulture);
            }
        }
        
        internal static string LimitlessRouterMonitor_OpenConnection_Opening {
            get {
                return ResourceManager.GetString("LimitlessRouterMonitor_OpenConnection_Opening", resourceCulture);
            }
        }
        
        internal static string LimitlessRouterMonitor_Run_Interrupted {
            get {
                return ResourceManager.GetString("LimitlessRouterMonitor_Run_Interrupted", resourceCulture);
            }
        }
        
        internal static string LimitlessRouterMonitor_Run_StoppingAfterException {
            get {
                return ResourceManager.GetString("LimitlessRouterMonitor_Run_StoppingAfterException", resourceCulture);
            }
        }
        
        internal static string LimitlessRouterMonitor_Run_ThreadRunning {
            get {
                return ResourceManager.GetString("LimitlessRouterMonitor_Run_ThreadRunning", resourceCulture);
            }
        }
        
        internal static string LimitlessRouterMonitor_TopologyPrefix {
            get {
                return ResourceManager.GetString("LimitlessRouterMonitor_TopologyPrefix", resourceCulture);
            }
        }
        
        internal static string LimitlessRouterService_EstablishConnection_ConnectingWithHost {
            get {
                return ResourceManager.GetString("LimitlessRouterService_EstablishConnection_ConnectingWithHost", resourceCulture);
            }
        }
        
        internal static string LimitlessRouterService_EstablishConnection_RouterCacheEmpty {
            get {
                return ResourceManager.GetString("LimitlessRouterService_EstablishConnection_RouterCacheEmpty", resourceCulture);
            }
        }
        
        internal static string LimitlessRouterService_EstablishConnection_SelectedHost {
            get {
                return ResourceManager.GetString("LimitlessRouterService_EstablishConnection_SelectedHost", resourceCulture);
            }
        }
        
        internal static string LimitlessRouterService_EstablishConnection_UsingProvidedConnectUrl {
            get {
                return ResourceManager.GetString("LimitlessRouterService_EstablishConnection_UsingProvidedConnectUrl", resourceCulture);
            }
        }
        
        internal static string LimitlessRouterService_EstablishConnection_WeightedRandomHostWeightPairs {
            get {
                return ResourceManager.GetString("LimitlessRouterService_EstablishConnection_WeightedRandomHostWeightPairs", resourceCulture);
            }
        }
        
        internal static string LimitlessRouterService_RetryConnect_FailedToConnectToHost {
            get {
                return ResourceManager.GetString("LimitlessRouterService_RetryConnect_FailedToConnectToHost", resourceCulture);
            }
        }
        
        internal static string LimitlessRouterService_RetryConnect_IncorrectConfiguration {
            get {
                return ResourceManager.GetString("LimitlessRouterService_RetryConnect_IncorrectConfiguration", resourceCulture);
            }
        }
        
        internal static string LimitlessRouterService_RetryConnect_NoRoutersAvailable {
            get {
                return ResourceManager.GetString("LimitlessRouterService_RetryConnect_NoRoutersAvailable", resourceCulture);
            }
        }
        
        internal static string LimitlessRouterService_RetryConnect_SelectedHostForRetry {
            get {
                return ResourceManager.GetString("LimitlessRouterService_RetryConnect_SelectedHostForRetry", resourceCulture);
            }
        }
        
        internal static string LimitlessRouterService_StartMonitoring_ErrorGettingRouters {
            get {
                return ResourceManager.GetString("LimitlessRouterService_StartMonitoring_ErrorGettingRouters", resourceCulture);
            }
        }
        
        internal static string LimitlessRouterService_SynchronouslyGetLimitlessRouters_ExceptionGettingRouters {
            get {
                return ResourceManager.GetString("LimitlessRouterService_SynchronouslyGetLimitlessRouters_ExceptionGettingRouters", resourceCulture);
            }
        }
        
        internal static string Error_MaxRetriesExceeded {
            get {
                return ResourceManager.GetString("Error_MaxRetriesExceeded", resourceCulture);
            }
        }
        
        internal static string LimitlessQueryHelper_CreateHost_InvalidRouterLoad {
            get {
                return ResourceManager.GetString("LimitlessQueryHelper_CreateHost_InvalidRouterLoad", resourceCulture);
            }
        }
        
        internal static string LimitlessRouterService_Error_FetchedEmptyRouterList {
            get {
                return ResourceManager.GetString("LimitlessRouterService_Error_FetchedEmptyRouterList", resourceCulture);
            }
        }
        
        internal static string LimitlessRouterService_Error_NoRoutersAvailable {
            get {
                return ResourceManager.GetString("LimitlessRouterService_Error_NoRoutersAvailable", resourceCulture);
            }
        }
        
        internal static string LimitlessRouterService_Error_UnableToConnectNoRoutersAvailable {
            get {
                return ResourceManager.GetString("LimitlessRouterService_Error_UnableToConnectNoRoutersAvailable", resourceCulture);
            }
        }
        
        internal static string Error_WeightedRandomInvalidHostWeightPairs {
            get {
                return ResourceManager.GetString("Error_WeightedRandomInvalidHostWeightPairs", resourceCulture);
            }
        }
        
        internal static string Error_WeightedRandomUnableToGetHost {
            get {
                return ResourceManager.GetString("Error_WeightedRandomUnableToGetHost", resourceCulture);
            }
        }
    }
}
